### ISSUE TITLE
Weired sys line

### ISSUE THREAD

**Issue by frennkie** [wc-duck/pymmh3#10]
Could you explain these two lines to me please https://github.com/wc-duck/pymmh3/blob/master/pymmh3.py#L20 + https://github.com/wc-duck/pymmh3/blob/master/pymmh3.py#L32 - what is the purpose of this?

Can't we simply use `import sys` and use it? Why rename and delete it?

Also in line https://github.com/wc-duck/pymmh3/blob/master/pymmh3.py#L451 `sys` is used although it doesn't exist.. so running it obviously give this error:

```
$: python3 pymmh3.py "foobar"
Traceback (most recent call last):
  File "pymmh3.py", line 451, in <module>
    sys.stdout.write( '"%s" = 0x%08X\n' % ( str_to_hash, hash( str_to_hash ) ) )
NameError: name 'sys' is not defined
```

**Comment by wc-duck** [comment]
I agree that it is weird but the "motivation" is here https://github.com/wc-duck/pymmh3/pull/3
I don't have the time to fix it now but feel free to add a pull request if you need it

**Comment by frennkie** [comment]
Well, ok. But you still need to do something about line 451.... I'd say: just import sys again there.

**Comment by wc-duck** [comment]
Thanks for the help btw!
