### ISSUE TITLE
Issues in Python3.4 

### ISSUE THREAD

**Issue by aliabbasrizvi** [wc-duck/pymmh3#6]
Hi

I was trying out pymmh3 with python3.4 and saw that on calling hash it gave me this error:

`TypeError: string argument without an encoding` on trying to do `key = bytearray( key )` (line 30)

The fix there is to call `encode()` on the string before trying to call bytearray on it. I was wondering if that is the expectation for every string. It only seems to be a problem on python 3.4. Once you call encode on the string and then try it works fine.

**Comment by wc-duck** [comment]
I'll have a look... I'm not really sure what the "correct" behavior is here. But I would say, "what mmh3 does is correct" for compliance.

Any suggestion on what is "correct" would be appreciated...

**Comment by wc-duck** [comment]
My first guess would also be to say that the encoding is not something that pymmh should deal with since the library can't do anything else than assume that you pass it raw bytes.

**Comment by aliabbasrizvi** [comment]
mmh3 works fine, in that it is able to send back the value as expected. I did not have to encode the string to be able to use it.

**Comment by swapniel99** [comment]
Hi,

The problem arises because python3 by default considers each string as Unicode.

**Comment by swapniel99** [comment]
The issue has been resolved.
